openapi: 3.0.1
info:
  title: Kubernetes Pod API
  description: API for retrieving pod information and updating pod resources
  version: v1.29.10+67d3387
servers:
- url: /
paths:
  /api/v1/namespaces/{namespace}/pods/{name}:
    get:
      summary: Get information about a specific pod
      parameters:
      - name: namespace
        in: path
        required: true
        schema: {}
      - name: name
        in: path
        required: true
        schema: {}
      responses:
        "200":
          description: Successful response
          content: {}
        "404":
          description: Pod not found
          content: {}
    patch:
      summary: Update pod resources and limits
      parameters:
      - name: namespace
        in: path
        required: true
        schema: {}
      - name: name
        in: path
        required: true
        schema: {}
      responses:
        "200":
          description: Successful update
          content: {}
        "400":
          description: Invalid request
          content: {}
        "404":
          description: Pod not found
          content: {}
components: {}
x-original-swagger-version: "2.0"
